version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
    - setup_remote_docker
    - checkout

    - restore_cache:
        key: app-{{ checksum "src/MyWeb/MyWeb.csproj" }}

    - run: |
        dotnet tool install -g cake.tool

    - run: |
        ~/.dotnet/tools/dotnet-cake -target=Publish
        docker-compose build

    - save_cache:
        paths:
        - ~/.m2
        key: app-{{ checksum "src/MyWeb/MyWeb.csproj" }}