version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
    - image: circleci/openjdk:8-jdk-stretch

    steps:
    - setup_remote_docker
    - checkout

    - restore_cache:
        key: app-{{ checksum "pom.xml" }}

    - run: |
        mvn assembly:assembly -DdescriptorId=jar-with-dependencies -DbuildId=${CIRCLE_BUILD_NUM}
        mkdir jar
        cp target/*.jar jar

    - save_cache:
        paths:
        - ~/.m2
        key: app-{{ checksum "pom.xml" }}

    - persist_to_workspace:
          root: .
          paths:
            - jar

    - store_artifacts:
        path: jar
